"use client";
import Head from "next/head";
import Image from "next/image";
import Services1 from "@/assets/icons/services-1.svg";
import Services2 from "@/assets/icons/services-2.svg";
import Services3 from "@/assets/icons/services-3.svg";
import Services4 from "@/assets/icons/services-4.svg";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Autoplay, Pagination } from "swiper/modules";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import ReviewsMasonryReact from "@/components/ReviewSection";
import WhatsAppButton from "@/components/WhatsappButton";
import BookingForm from "@/components/BookingForm";
import fleets from "@/data/fleets";
import { useState } from "react";
import BookNowModal from "@/components/BookNowModal";

const services = [
  {
    title: "Airport Transfer",
    Icon: Services3,
    desc: "Effortless airport pick-ups and drop-offs in well-maintained cars with punctual, polite chauffeurs.",
  },
  {
    title: "Luxury Sedan Rentals",
    Icon: Services2,
    desc: "Elevate your journey with stylish luxury sedans—perfect for business travelers and upscale transfers.",
  },
  {
    title: "Outstation & Road Trips",
    Icon: Services1,
    desc: "Comfortable long-distance outstation trips with spacious vehicles oriented for safety and convenience.",
  },
  {
    title: "Hourly City Rentals",
    Icon: Services4,
    desc: "Flexible hourly rentals for city errands, short trips, or point-to-point travel, hassle-free and affordable.",
  },
];

// const fleets = [
//   {
//     id: 1,
//     image: "/images/dzire.png",
//     name: "Dzire",
//     rate: "₹12/km",
//     seater: "4",
//     type: "Sedan",
//   },
//   {
//     id: 2,
//     image: "/images/aura.png",
//     name: "Aura",
//     rate: "₹12/km",
//     seater: "4",
//     type: "Sedan",
//   },
//   {
//     id: 3,
//     image: "/images/ertiga.png",
//     name: "Ertiga",
//     rate: "₹14/km",
//     seater: "6",
//     type: "SUV",
//   },
//   {
//     id: 4,
//     image: "/images/innova.png",
//     name: "Innova",
//     rate: "₹18/km",
//     seater: "6",
//     type: "SUV",
//   },
//   {
//     id: 5,
//     image: "/images/crysta.png",
//     name: "Innova Crysta",
//     rate: "₹20/km",
//     seater: "7",
//     type: "SUV",
//   },
//   {
//     id: 6,
//     image: "/images/mini-bus.png",
//     name: "Mini Bus",
//     rate: "",
//     seater: "24 / 32 / 40 / 45 / 55",
//     type: "Mini Bus",
//   },
//   {
//     id: 7,
//     image: "/images/tempo.png",
//     name: "Tempo Travellers",
//     rate: "NA",
//     seater: "13 / 17",
//     type: "Tempo Travellers",
//   },
// ];

export default function Home() {
  // const [modalOpen, setModalOpen] = useState(false);
  // const [selectedCar, setSelectedCar] = useState(null);
  const [isModalOpen, setModalOpen] = useState(false);
  const [selectedCar, setSelectedCar] = useState(null);

  const openModal = (carName) => {
    setSelectedCar(carName || null);
    setModalOpen(true);
  };
  // const openModal = (carName) => {
  //   setSelectedCar(carName || null);
  //   setModalOpen(true);
  // };
  return (
    <>
      <Head>
        <title>Safe Tours And Travels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="home" className="hero-section side-space">
        <div className="hero-parent">
          <div className="hero-content">
            <h1 className="page-heading">Anytime, Anywhere Travel Solutions</h1>
            {/* <p>Premium Car Rentals & Tours</p> */}
            <p className="hero-para">
              From quick city rides to long-distance getaways, our modern fleet
              and professional chauffeurs ensure comfort, safety, and style on
              every journey. Experience hassle-free travel that’s always on
              time, wherever you need to go.
            </p>
            <button onClick={() => openModal(null)} className="primary-button">
              Book Your Ride Today
            </button>
          </div>
        </div>
      </section>

      <BookingForm />

      <section id="about-us" className="about-us side-space">
        <div className="row">
          <div className="col-md-6"></div>
          <div className="col-md-6">
            <h2 className="section-heading">About Us</h2>
            <h4>
              Your Trusted Partner for Comfortable, Reliable, and Premium Travel
            </h4>
            <p>
              At <span className="safe-text">Safe Tours And Travels</span>, we
              provide reliable, comfortable, and safe transportation services
              for every journey. From airport pickups and drop-offs to full-day
              sightseeing tours, our professional drivers and well-maintained
              fleet are dedicated to ensuring you travel with peace of mind.
              Whether it's a quick city ride or a long-distance trip, we
              prioritize punctuality, safety, and customer satisfaction every
              step of the way.
            </p>

            <p>
              We offer a wide range of travel solutions including corporate
              transfers, family trips, wedding transportation, and customized
              tour packages designed to meet your needs. With our commitment to
              excellence, modern vehicles, and friendly service,{" "}
              <span className="safe-text">Safe Tours And Travels </span>
              is your trusted partner for a smooth and enjoyable journey, no
              matter where you're headed.
            </p>

            {/* <button className="primary-button">Know More</button> */}
          </div>
        </div>
      </section>

      <section id="services" className="side-space section-space services">
        <div className="services-inner side-space section-space">
          <h2 className="section-heading text-center">Our Services</h2>
          <div className="row g-3">
            {services.map((service, idx) => {
              const Icon = service.Icon; // grab component
              return (
                <div key={idx} className="col-md-3">
                  <div className="service-card text-left">
                    <Icon className="service-icon mb-3" />{" "}
                    {/* SVG rendered directly */}
                    <h4 className="services-title">{service.title}</h4>
                    <p className="service-desc mb-0">{service.desc}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      <section id="our-cars" className="our-fleets side-space">
        <div className="car-swiper">
          <h2 className="section-heading text-center">Our Fleets</h2>
          <h4 className="text-center">
            Explore our diverse fleet of vehicles, designed to meet all your
            travel needs with comfort and style.
          </h4>
          {/* Car Swiper Component */}
          <div className="car-swiper mt-4">
            <Swiper
              modules={[Navigation, Pagination, Autoplay]}
              // navigation
              pagination={{ clickable: true }}
              autoplay={{
                delay: 30000, // time in ms before slide changes
                disableOnInteraction: false, // keeps autoplay after user swipes
              }}
              loop={true} // optional for continuous loop
              spaceBetween={20}
              breakpoints={{
                1024: { slidesPerView: 5 },
                768: { slidesPerView: 3 },
                480: { slidesPerView: 2 },
                0: { slidesPerView: 1 },
              }}
            >
              {fleets.map((fleet, index) => (
                <SwiperSlide key={fleet.id}>
                  <div
                    className="car-card"
                    // style={{ "--shine-delay": `${index * 0.3}s` }}
                  >
                    <img
                      src={fleet.image}
                      alt={fleet.name}
                      // width={auto}
                      // height={auto}
                      className="img-fluid fleet-image"
                    />
                    <span className="car-type">{fleet.type}</span>
                    <h4 className="car-name">{fleet.name}</h4>
                    <div className="car-info">
                      <div className="car-price d-flex justify-content-between mb-2">
                        <p className="mb-0">Rate</p>
                        <p className="mb-0">{fleet.rate}</p>
                      </div>

                      <div className="car-seater d-flex justify-content-between mb-2">
                        <p className="mb-0">Seater</p>
                        <p className="mb-0">{fleet.seater}</p>
                      </div>
                    </div>
                    <div className="text-center">
                      <button
                        onClick={() => openModal(fleet.name)}
                        className="primary-button mt-3"
                      >
                        Book Now
                      </button>
                    </div>
                  </div>
                </SwiperSlide>
              ))}
            </Swiper>
          </div>
        </div>
      </section>

      <ReviewsMasonryReact columns={3} />

      <WhatsAppButton />

      {/* <BookingModal
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        selectedCar={selectedCar}
      /> */}
      <BookNowModal
        isOpen={isModalOpen}
        onClose={() => setModalOpen(false)}
        carSelected={selectedCar}
      />
    </>
  );
}
